Repository Roestlab/massdash, pull requests merged in 2024-03, with the labels that each got.

#118 Update/docs
  README.md
  docs/Installation.rst
  docs/README.md
  docs/conf.py
  docs/installation_docs/assets/img/macos_conda_cmd_massdash_gui_help.png
  docs/installation_docs/assets/img/macos_conda_cmd_massdash_gui_run.png
  docs/installation_docs/assets/img/macos_conda_create_env.png
  docs/installation_docs/assets/img/macos_conda_env_activate.png
  docs/installation_docs/assets/img/macos_git_developer_tools.png
  docs/installation_docs/assets/img/macos_massdash_gui.png
  docs/installation_docs/assets/img/macos_massdash_gui_example.png
  docs/installation_docs/assets/img/macos_massdash_install.png
  docs/installation_docs/assets/img/ubuntu_conda_cmd_massdash_gui_help.png
  docs/installation_docs/assets/img/ubuntu_conda_cmd_massdash_gui_run.png
  docs/installation_docs/assets/img/ubuntu_conda_env_activate.png
  docs/installation_docs/assets/img/ubuntu_conda_env_create.png
  docs/installation_docs/assets/img/ubuntu_massdash_gui.png
  docs/installation_docs/assets/img/ubuntu_massdash_gui_example.png
  docs/installation_docs/assets/img/ubuntu_massdash_install.png
  docs/installation_docs/assets/img/windows_anaconda_nav_cmd_prompt_launch.png
  docs/installation_docs/assets/img/windows_conda_cmd_activate_env.png
  docs/installation_docs/assets/img/windows_conda_cmd_install_massdash.png
  docs/installation_docs/assets/img/windows_conda_cmd_massdash_gui_help.png
  docs/installation_docs/assets/img/windows_conda_cmd_massdash_gui_run.png
  docs/installation_docs/assets/img/windows_conda_cmd_prompt_create_env.png
  docs/installation_docs/assets/img/windows_massdash_gui.png
  docs/installation_docs/assets/img/windows_massdash_gui_example.png
  docs/installation_docs/macos_installation.rst
  docs/installation_docs/ubuntu_installation.rst
  docs/installation_docs/windows_installation.rst
Labels: documentation

#129 docs: update docs for release
  README.md
  docs/GUI.rst
  docs/Installation.rst
  docs/index.rst
Labels: documentation, enhancement

#128 add: button to terminate massdash
  massdash/gui.py
  massdash/util.py
  pyproject.toml
  requirements.txt
  setup.cfg
Labels: enhancement, GUI
