Repository Roestlab/massdash, pull requests merged in 2024-01, with the labels that each got.

#91 [UPDATE] search results demo data url blob to raw
  massdash/gui.py
Labels: bug

#93 Patch/home button
  massdash/constants.py
  massdash/gui.py
  massdash/plotting/InteractivePlotter.py
  massdash/util.py
Labels: enhancement, GUI

#95 Fix/test
  massdash/loaders/GenericChromatogramLoader.py
  massdash/loaders/GenericSpectrumLoader.py
  massdash/structs/TransitionGroup.py
  massdash/util.py
  test/loaders/snapshots/snap_test_OSWDataAccess.py
  test/loaders/snapshots/snap_test_SqMassDataAccess.py
  test/loaders/snapshots/snap_test_SqMassLoader.py
  test/loaders/snapshots/test_snap_SqMassLoader.py
  test/loaders/test_OSWDataAccess.py
  test/loaders/test_SqMassDataAccess.py
  test/loaders/test_SqMassLoader.py
  test/peakPickers/snapshots/snap_test_pyMRMTransitionGroupPicker.py
  test/peakPickers/test_MRMTransitionGroupPicker.py
Labels: tests

#99 [CHANGE] ui option name for feature file boundaries
  massdash/server/ExtractedIonChromatogramAnalysisServer.py
  massdash/server/OneDimensionPlotterServer.py
  massdash/server/PeakPickingServer.py
  massdash/server/RawTargetedExtractionAnalysisServer.py
  massdash/ui/PeakPickingUISettings.py
Labels: refactor

#100 Patch/peak boundary int
  docs/python_docs/Advanced Plotting.ipynb
  docs/python_docs/Plotting1D.ipynb
  manuscript/main_figures/Figure-3-Features-Comparison.ipynb
  manuscript/main_figures/Figure-4-Extraction-Optimization.ipynb
  manuscript/main_figures/Figure-5-Peak-Picking-Demonstration.ipynb
  massdash/loaders/GenericLoader.py
  massdash/plotting/GenericPlotter.py
  massdash/plotting/InteractivePlotter.py
  massdash/structs/TransitionGroup.py
Labels: enhancement

#103 fix: remove window_size arg from Conformer call
  massdash/server/ExtractedIonChromatogramAnalysisServer.py
Labels: bug

#109 Bug/conformer preprocessor
  massdash/structs/Data1D.py
  test/structs/test_Data1D.py
Labels: bug

#111 Bug/mrmpeakpicking none smoother
  docs/python_docs/Peak Picking.ipynb
  massdash/constants.py
  massdash/plotting/GenericPlotter.py
  massdash/plotting/InteractivePlotter.py
  massdash/structs/TransitionGroup.py
  massdash/ui/ChromatogramPlotUISettings.py
  massdash/ui/MRMTransitionGroupPickerUISettings.py
Labels: bug
